"""add unique constraints to Favorite

Revision ID: d0e35e3728e1
Revises: 21bbe4f7af8f
Create Date: 2025-10-31 11:57:03.232629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e35e3728e1'
down_revision = '21bbe4f7af8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_person', ['user_id', 'person_id'])
        batch_op.create_unique_constraint('uix_user_planet', ['user_id', 'planet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_planet', type_='unique')
        batch_op.drop_constraint('uix_user_person', type_='unique')

    # ### end Alembic commands ###
